spring:
  application:
    name: notes
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: utkarsh
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8000

